version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  build-docker-dev:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: DockerBuildDev
          command: mvn clean package -Pprod jib:build -DskipTests -Djib.to.tags=latest-develop
  build-docker-master:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: DockerBuildMaster
          command: mvn clean package -Pprod jib:build -DskipTests -Djib.to.tags=latest

workflows:
  simple-ci:
    jobs:
      - build-and-test
      - build-docker-dev:
          filters:
            branches:
              only:
                - develop
      - build-docker-master:
          filters:
            branches:
              only:
                - master

